---
new_page_extension: md
auto_deploy: false
admin_path: "/site/public/admin"
webhook_url: 
sections:
- type: directory
  path: site/src
  label: Pages
  create: documents
  match: "*"
  new_doc_ext: md
  templates:
  - page-default
upload_dir: images
public_path: https://res.cloudinary.com/______/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: site/dist
  install_dependencies_command: cd site && npm ci
  preview_docker_image: node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
